name: Mirroring

on: [push, delete]

jobs:
  to_gitea:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: 'ssh://git@git-ssh.dev.cloud.kadaster.nl:443/dst/dst-secured-sparql-endpoint-mirror.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          # disable known_hosts until PR is merged: https://github.com/yesolutions/mirror-action/pull/19
          GIT_SSH_NO_VERIFY_HOST: "true"
          # GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}
